package com.tencent.msdk.dns.core.rest.share;

public interface ErrorCode {

    int ANDROID_CLIENT_ERROR_CODE_OFFSET = 1000;
//    int IOS_CLIENT_ERROR_CODE_OFFSET = 2000;

    int CONNECT_ERROR_CODE_OFFSET = 10000;
    int REQUEST_ERROR_CODE_OFFSET = 20000;
    int RESPONSE_ERROR_CODE_OFFSET = 30000;
    int PARSE_ERROR_CODE_OFFSET = 40000;

    int SUCCESS = 0;
    int NOT_LOOKUP = 1;
    int LOOKUP_TIMEOUT = 2;
    int NO_RECORD = 3;

    int CREATE_SOCKET_FAILED_ERROR_CODE = ANDROID_CLIENT_ERROR_CODE_OFFSET + 1;
//    int SET_SOCKET_TIMEOUT_FAILED_ERROR_CODE = ANDROID_CLIENT_ERROR_CODE_OFFSET + 2;
//    int OPEN_CHANNEL_FAILED_ERROR_CODE = ANDROID_CLIENT_ERROR_CODE_OFFSET + 3;
    int SET_NON_BLOCK_FAILED_ERROR_CODE = ANDROID_CLIENT_ERROR_CODE_OFFSET + 4;
    int REGISTER_CHANNEL_FAILED_ERROR_CODE = ANDROID_CLIENT_ERROR_CODE_OFFSET + 5;
    int GET_TARGET_SOCKET_ADDRESS_FAILED_ERROR_CODE = ANDROID_CLIENT_ERROR_CODE_OFFSET + 6;
    int ENCRYPT_REQUEST_CONTENT_FAILED_ERROR_CODE = ANDROID_CLIENT_ERROR_CODE_OFFSET + 7;
    int CREATE_REQUEST_PACKET_CONTENT_FAILED_ERROR_CODE = ANDROID_CLIENT_ERROR_CODE_OFFSET + 8;

    int CONNECT_FAILED_ERROR_CODE =
            CONNECT_ERROR_CODE_OFFSET + ANDROID_CLIENT_ERROR_CODE_OFFSET + 1;

    int REQUEST_FAILED_ERROR_CODE =
            REQUEST_ERROR_CODE_OFFSET + ANDROID_CLIENT_ERROR_CODE_OFFSET + 1;

    int RESPONSE_FAILED_NEED_CONTINUE_ERROR_CODE =
            RESPONSE_ERROR_CODE_OFFSET + ANDROID_CLIENT_ERROR_CODE_OFFSET + 1;

    int RESPONSE_FAILED_FOR_EXCEPTION_ERROR_CODE =
            RESPONSE_ERROR_CODE_OFFSET + ANDROID_CLIENT_ERROR_CODE_OFFSET + 2;

    int DECRYPT_RESPONSE_CONTENT_FAILED_ERROR_CODE =
            PARSE_ERROR_CODE_OFFSET + ANDROID_CLIENT_ERROR_CODE_OFFSET + 1;
    int PARSE_RESPONSE_CONTENT_FAILED_ERROR_CODE =
            PARSE_ERROR_CODE_OFFSET + ANDROID_CLIENT_ERROR_CODE_OFFSET + 2;
}
